steps = 4
n_runs = 1
img_path = 'datasets/COVIDX/images/'
num_cls = 4
unfreeze_clip = False
paper = True
data_root = 'exp/linear_probe/COVIDX'
img_split_path = 'datasets/COVIDX/splits'
cls_names = ['Lung Opacity', 'Normal', 'Viral Pneumonia', 'COVID']
img_ext = ''
clip_model = 'ViT-B/16'
lr = 0.001
bs = 128
n_shots = 'all'
dataset = 'COVIDX'
